vars:
  - top: ../..
  # OECD data has changed format
stages:
  download:
    cmd: PYTHONPATH=${top} python download.py
    always_changed: true
    deps:
      - download.py
    outs:
      - ${top}/data/raw/oecd/lfs_by_sex_and_age.csv:
          cache: false
      - ${top}/data/raw/oecd/neet.csv:
          cache: false
      - ${top}/data/raw/oecd/wage_levels.csv:
          cache: false
