vars:
  - top: ../..
  # OECD data has changed format
stages:
  download:
    cmd: PYTHONPATH=${top} python download.py
    always_changed: true
    deps:
      - download.py
    outs:
      - ${top}/data/raw/oecd/lfs_by_sex_and_age.csv:
          cache: false
      - ${top}/data/raw/oecd/neet.csv:
          cache: false
      - ${top}/data/raw/oecd/wage_levels.csv:
          cache: false
#   transform:
#     cmd: papermill --no-progress-bar --no-report-mode transform.ipynb ${top}/output/oecd-transform.ipynb
#     deps:
#       - transform.ipynb
#       - ${top}/data/raw/oecd/
#     outs:
#       - ${top}/data/processed/oecd/lfs_by_sex_and_age.csv:
#           cache: false
#       - ${top}/data/processed/oecd/neet.csv:
#           cache: false
#       - ${top}/data/processed/oecd/wage_levels.csv:
#           cache: false

  transform-neet:
    cmd: python transform-neet.py
    deps:
      - transform-neet.py
      - ${top}/data/raw/oecd/neet.csv
    outs:
      - ${top}/data/processed/oecd/neet.csv:
          cache: false

  transform-wage-levels:
    cmd: python transform-wage-levels.py
    deps:
      - transform-wage-levels.py
      - ${top}/data/raw/oecd/wage_levels.csv
    outs:
      - ${top}/data/processed/oecd/wage_levels.csv:
          cache: false
