vars:
  - TOP: ../..
stages:
  download:
    foreach: '${sources}'
    do:
      cmd: PYTHONPATH=${TOP} python download.py ${key} "${item.url}"
      always_changed: true
      deps:
        - download.py
      outs:
        - ${TOP}/data/raw/${key}.csv:
            cache: false
  process:
    foreach: '${sources}'
    do:
      cmd: papermill process.ipynb ${TOP}/output/ons-process-${key}.ipynb -p dataset ${key} -p url "${item.url}"
      deps:
        - process.ipynb
        - ${TOP}/data/raw/${key}.csv
      outs:
        - ${TOP}/data/processed/${key}.csv:
            cache: false
        - ${TOP}/data/metadata/codes/${key}-codes.csv:
            cache: false
